"""_fork_pcs_floor_scaling — does the UNTRAINED-reservoir floor RISE with core size (n_hidden)?

`_fork_pcs_emergence_derisk.py` compares the emergent "place code" R^2 against an
UNTRAINED-reservoir floor (a fresh, never-trained core replayed on the same input
sequence). The headline finding is that after long training, place drifts to
AT-OR-BELOW that floor at n_hidden=512 (e.g. the rate 6-seed artifact:
place_r2 in [0.598, 0.691] vs floor_untrained in [0.632, 0.735] — trained is at/
below the floor on every one of 6 seeds).

OPEN QUESTION this runner answers: is the untrained floor itself a CAPACITY
ARTIFACT — does a bigger random reservoir just decode position better purely
from its richer (still untrained) dynamics, independent of any learning at all?
If so, "place fell below the untrained floor" at n_hidden=512 may be partly
"the floor is high because 512 is already a large random projection", not only
"the trained core specifically lost/never-acquired a place code".

METHOD (reuses the parent runner's exact decode machinery — no new decoder):
  * `_ridge_r2` (ridge regression, closed-form, standardized, held-out R^2) is
    IMPORTED verbatim from research.runners.fork_pcs_world (the same function
    _fork_pcs_emergence_derisk.py imports and uses for the "presence" decodes).
  * The 70/30 train/test split uses the identical convention:
    `np.random.default_rng(seed + 5).permutation(n)`, cut at 0.7*n — SAME as
    `_fork_pcs_emergence_derisk._r2_with_floors` / `run_smoke`, so R^2 numbers
    here are directly comparable to the existing 6-seed artifacts.
  * The untrained floor is measured the same way as
    `_fork_pcs_emergence_derisk.replay_untrained`: build a FRESH core at
    `seed + 777` (never trained; `sub.freeze()` before any `observe()` call so
    no weight update ever happens), then call `sub.observe(v1, a_prev, d)` over
    a FIXED input sequence (no `act()`/`step()` — the world transitions were
    already baked into the sequence when it was captured).

DESIGN — one exploration sequence per seed, reused across every n_hidden
--------------------------------------------------------------------------
In the parent runner the exploration sequence that gets replayed through the
untrained floor is generated by the TRAINED core's own (explore_eps=0.4)
policy. Here there is no trained core to author it (that would confound floor
vs core-size with floor vs policy-quality), so the sequence is generated once
per seed by a UNIFORM-RANDOM action policy driving the world (independent of
any core / of n_hidden — the same "random-walk env sequence" idiom already
used by `fork_pcs_world._collect_stationary_eval`), and the IDENTICAL sequence
is then replayed through a fresh untrained core at every n_hidden. This holds
the "what the agent saw" variable fixed and isolates the "how big is the
random reservoir doing the mixing" variable — the correct ceteris-paribus
design for the capacity-artifact question.

OPTIONAL SECONDARY (contrast, --train-contrast; on by default, cheap on CPU —
benchmarked ~5 min at n_hidden=2048 for n_train=18000 on this machine): for
each (n_hidden, seed), also train a FRESH core online with the curiosity/
explore policy (`sub.act(h, explore_eps=0.2)`, mirroring
`_fork_pcs_emergence_derisk.run_seed`'s train step exactly) for `--n-train`
steps, probe it (frozen, explore_eps=0.4, matching `run_seed`'s probe step),
decode place R^2, and compare against a SIZE-MATCHED untrained floor computed
on that SAME probe's exact input sequence (apples-to-apples with the trained
number, exactly as `run_seed` does for its single n_hidden=512 arm).

Run:
  # tiny end-to-end self-test (numpy, seconds)
  SIM_BACKEND=numpy python -m research.runners._fork_pcs_floor_scaling --smoke

  # full sweep (untrained-floor curve only; CPU, ~1 minute)
  SIM_BACKEND=numpy python -m research.runners._fork_pcs_floor_scaling --no-train-contrast \\
      --out research/findings/raw/_fork_pcs_floor_scaling.json

  # full sweep + optional trained-core contrast (CPU, ~30 minutes; the default)
  SIM_BACKEND=numpy python -m research.runners._fork_pcs_floor_scaling \\
      --out research/findings/raw/_fork_pcs_floor_scaling.json
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from typing import Dict, List, Optional, Tuple

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_HERE, "..", ".."))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from sim.pcs_substrate import PredictiveContinualSubstrate, PCSConfig
from research.runners.fork_pcs_world import WorldConfig, ForkPCSWorld, N_ACTIONS, _ridge_r2
# gap#5 discipline: measuring both arms is not the same as attributing the difference — route the
# trained-vs-untrained place-decode advantage through an explicit attribution call.
from tools.lab import attributable_to

N_HIDDEN_SIZES_DEFAULT = [128, 256, 512, 1024, 2048]
SEEDS_DEFAULT = [42, 43, 44]
N_LATENT = 64          # matches _fork_pcs_emergence_derisk.run_seed's n_latent
N_PROBE_DEFAULT = 8000  # matches run_seed's n_probe (comparable R^2 magnitudes)
N_TRAIN_DEFAULT = 18000  # optional secondary arm; within the requested 15k-20k


def _f(x):
    try:
        return round(float(x), 4)
    except Exception:
        return None


def _to_host(x):
    return np.asarray(x.get() if hasattr(x, "get") else x, dtype=np.float32)


# ─────────────────────────────────────────────────────────────────────────────
# exploration-sequence capture (pure environment; independent of any core)
# ─────────────────────────────────────────────────────────────────────────────
def collect_exploration_sequence(wcfg: WorldConfig, n_probe: int, seed: int):
    """Drive the world with UNIFORM-RANDOM actions for n_probe steps (independent of
    any core/n_hidden — mirrors fork_pcs_world._collect_stationary_eval's random-walk
    idiom). Returns (input_seq, POS, RAW):
      input_seq : list of (v1_host, a_prev, d) triples — the exact untrained-replay
                  format `_fork_pcs_emergence_derisk.replay_untrained` consumes.
      POS       : (n,2) float32 ground-truth agent position BEFORE each step (aligned
                  to the observation, same convention as `rollout`'s `pos_before`).
      RAW       : (n, n_v1) float32 raw V1 features of the current crop (the raw-V1
                  sanity floor; independent of n_hidden by construction).
    """
    world = ForkPCSWorld(wcfg)
    rng = np.random.default_rng(seed + 4242)
    input_seq: List[Tuple[np.ndarray, int, np.ndarray]] = []
    POS, RAW = [], []
    a_prev = -1
    for _ in range(n_probe):
        d = world.drive_afferent()
        v1 = world.crop_v1feat()
        v1_host = _to_host(v1)
        pos_before = world.agent
        a = int(rng.integers(N_ACTIONS))
        world.step(a)
        input_seq.append((v1_host, a_prev, np.asarray(d, dtype=np.float32)))
        POS.append(np.asarray(pos_before, dtype=np.float32))
        RAW.append(v1_host)
        a_prev = a
    return input_seq, np.asarray(POS), np.asarray(RAW)


def replay_through_core(sub: PredictiveContinualSubstrate, input_seq) -> np.ndarray:
    """Replay a FIXED (v1, a_prev, d) sequence through `sub` via observe() ONLY (no
    act()/step() — the world transitions already happened when the sequence was
    captured). Identical protocol to `_fork_pcs_emergence_derisk.replay_untrained`,
    generalized to any already-constructed `sub` (trained or untrained)."""
    H = []
    for (v1, ap, d) in input_seq:
        h = sub.observe(v1, ap, d)
        H.append(_to_host(h))
    return np.asarray(H)


# ─────────────────────────────────────────────────────────────────────────────
# decode: EXACT parent split convention + the imported _ridge_r2 (no new decoder)
# ─────────────────────────────────────────────────────────────────────────────
def _split(n, seed):
    perm = np.random.default_rng(seed + 5).permutation(n)
    cut = int(0.7 * n)
    return perm[:cut], perm[cut:]


def _r2_place(H, POS, seed):
    tr, te = _split(len(POS), seed)
    return _ridge_r2(H[tr], POS[tr], H[te], POS[te])


def _r2_shuffle(H, POS, seed):
    """Sanity floor: break the h<->label correspondence (temporal-shuffle control,
    same recipe as _fork_pcs_emergence_derisk._r2_with_floors's floor_shuffle)."""
    n = len(POS)
    tr, te = _split(n, seed)
    sh = np.random.default_rng(seed + 9).permutation(n)
    return _ridge_r2(H[tr], POS[sh][tr], H[te], POS[sh][te])


# ─────────────────────────────────────────────────────────────────────────────
# core deliverable: untrained-floor place R^2 vs n_hidden
# ─────────────────────────────────────────────────────────────────────────────
def untrained_floor_for_size(n_hidden, seed, wcfg, input_seq, POS, RAW,
                              n_latent=N_LATENT, units="rate", encoder="learned_ema"):
    """FRESH UNTRAINED core at n_hidden (seed+777, matching replay_untrained's
    floor-seed convention), frozen, replayed on the FIXED exploration sequence.
    Returns the untrained-floor place R^2 + the raw-V1 and shuffle sanity floors
    on the identical split."""
    sub = PredictiveContinualSubstrate(PCSConfig(
        n_hidden=n_hidden, feat_dim=wcfg.n_v1, n_latent=n_latent, n_actions=N_ACTIONS,
        n_drive=4, units=units, encoder=encoder, seed=seed + 777))
    sub.freeze()
    t0 = time.time()
    H_un = replay_through_core(sub, input_seq)
    elapsed = time.time() - t0
    r2_un = _r2_place(H_un, POS, seed)
    r2_raw = _r2_place(RAW, POS, seed)
    r2_sh = _r2_shuffle(H_un, POS, seed)
    return {"n_hidden": n_hidden, "seed": seed, "n_probe": len(POS),
            "r2_untrained": _f(r2_un), "r2_rawv1": _f(r2_raw), "r2_shuffle": _f(r2_sh),
            "elapsed_s": round(elapsed, 2)}


# ─────────────────────────────────────────────────────────────────────────────
# optional secondary: trained-core place R^2 for contrast
# ─────────────────────────────────────────────────────────────────────────────
def train_and_probe_for_size(n_hidden, seed, wcfg, n_train, n_probe,
                              n_latent=N_LATENT, units="rate", encoder="learned_ema"):
    """Train a FRESH core online (curiosity/explore policy, explore_eps=0.2 — exactly
    `_fork_pcs_emergence_derisk.run_seed`'s train step) for n_train steps, PROBE it
    frozen (explore_eps=0.4, matching run_seed's probe step) for n_probe steps
    collecting its OWN input sequence, decode place R^2, and compute a SIZE-MATCHED
    untrained floor on that SAME probe sequence (apples-to-apples, mirroring
    run_seed's own trained-vs-floor comparison, restricted to the place faculty)."""
    world = ForkPCSWorld(wcfg)
    scfg = PCSConfig(n_hidden=n_hidden, feat_dim=wcfg.n_v1, n_latent=n_latent, n_actions=N_ACTIONS,
                      n_drive=4, tbptt_T=18, units=units, encoder=encoder, seed=seed)
    sub = PredictiveContinualSubstrate(scfg)
    sub.unfreeze()
    a_prev = -1
    t0 = time.time()
    for _ in range(n_train):
        d = world.drive_afferent(); v1 = world.crop_v1feat()
        h = sub.observe(v1, a_prev, d)
        a = sub.act(h, explore_eps=0.2)
        r, _ = world.step(a)
        sub.learn(r)
        a_prev = a
    train_elapsed = time.time() - t0

    sub.freeze()
    H, POS, RAW, input_seq = [], [], [], []
    for _ in range(n_probe):
        d = world.drive_afferent(); v1 = world.crop_v1feat()
        v1_host = _to_host(v1)
        pos_before = world.agent
        h = sub.observe(v1, a_prev, d)
        a = sub.act(h, explore_eps=0.4)
        world.step(a)
        H.append(_to_host(h)); POS.append(np.asarray(pos_before, dtype=np.float32)); RAW.append(v1_host)
        input_seq.append((v1_host, a_prev, np.asarray(d, dtype=np.float32)))
        a_prev = a
    H = np.asarray(H); POS = np.asarray(POS); RAW = np.asarray(RAW)

    floor_sub = PredictiveContinualSubstrate(PCSConfig(
        n_hidden=n_hidden, feat_dim=wcfg.n_v1, n_latent=n_latent, n_actions=N_ACTIONS,
        n_drive=4, units=units, encoder=encoder, seed=seed + 777))
    floor_sub.freeze()
    H_un = replay_through_core(floor_sub, input_seq)

    r2_trained = _r2_place(H, POS, seed)
    r2_untrained_matched = _r2_place(H_un, POS, seed)
    r2_raw = _r2_place(RAW, POS, seed)
    # ATTRIBUTION: what fraction of the trained core's place decode is attributable to TRAINING vs the
    # size-matched untrained-reservoir baseline? A small fraction = the decode is mostly the reservoir's
    # richer dynamics (the capacity-artifact reading), NOT learning — the whole point of this runner.
    frac_from_training = attributable_to(
        "place-decode trained-vs-untrained n_hidden=%d seed=%d" % (n_hidden, seed),
        r2_trained, r2_untrained_matched)
    return {"n_hidden": n_hidden, "seed": seed, "n_train": n_train, "n_probe": n_probe,
            "r2_trained": _f(r2_trained), "r2_untrained_matched_probe": _f(r2_untrained_matched),
            "r2_rawv1": _f(r2_raw),
            "advantage_trained_minus_untrained": _f(r2_trained - r2_untrained_matched),
            "frac_place_decode_from_training": _f(frac_from_training) if frac_from_training is not None else None,
            "train_elapsed_s": round(train_elapsed, 1)}


# ─────────────────────────────────────────────────────────────────────────────
# aggregation + verdict
# ─────────────────────────────────────────────────────────────────────────────
def _rank(a):
    order = np.argsort(a, kind="stable")
    ranks = np.empty_like(order, dtype=np.float64)
    ranks[order] = np.arange(len(a), dtype=np.float64)
    return ranks


def _spearman(x, y):
    rx, ry = _rank(np.asarray(x, dtype=np.float64)), _rank(np.asarray(y, dtype=np.float64))
    rx = rx - rx.mean(); ry = ry - ry.mean()
    denom = (np.sqrt((rx * rx).sum()) * np.sqrt((ry * ry).sum())) + 1e-12
    return float((rx * ry).sum() / denom)


def aggregate_floor(per_size_seed: List[dict], sizes: List[int]) -> dict:
    curve = []
    for nh in sizes:
        vals = [r["r2_untrained"] for r in per_size_seed if r["n_hidden"] == nh and r["r2_untrained"] is not None]
        raws = [r["r2_rawv1"] for r in per_size_seed if r["n_hidden"] == nh and r["r2_rawv1"] is not None]
        shs = [r["r2_shuffle"] for r in per_size_seed if r["n_hidden"] == nh and r["r2_shuffle"] is not None]
        curve.append({
            "n_hidden": nh, "n": len(vals),
            "r2_untrained_mean": _f(np.mean(vals)) if vals else None,
            "r2_untrained_sd": _f(np.std(vals, ddof=1)) if len(vals) > 1 else (0.0 if vals else None),
            "r2_rawv1_mean": _f(np.mean(raws)) if raws else None,
            "r2_shuffle_mean": _f(np.mean(shs)) if shs else None,
        })
    return {"curve": curve}


def verdict_floor(per_size_seed: List[dict], curve: List[dict]) -> dict:
    sizes = [c["n_hidden"] for c in curve if c["r2_untrained_mean"] is not None]
    means = [c["r2_untrained_mean"] for c in curve if c["r2_untrained_mean"] is not None]
    if len(sizes) < 2:
        return {"note": "insufficient sizes for a verdict"}
    all_sizes = np.asarray([r["n_hidden"] for r in per_size_seed], dtype=np.float64)
    all_r2 = np.asarray([r["r2_untrained"] for r in per_size_seed], dtype=np.float64)
    rho = _spearman(all_sizes, all_r2)
    smallest, largest = means[0], means[-1]
    delta = largest - smallest
    monotonic = all(means[i + 1] >= means[i] - 0.02 for i in range(len(means) - 1))  # small-tolerance non-decreasing
    # a "meaningful" rise: >= 0.05 R^2 units end-to-end (same FLOOR_MARGIN convention the parent
    # runner uses to call a decode a real beat, not noise) AND a clearly positive rank correlation.
    floor_rises_with_size = bool(delta >= 0.05 and rho >= 0.5)
    return {
        "n_hidden_smallest": sizes[0], "n_hidden_largest": sizes[-1],
        "floor_mean_at_smallest": _f(smallest), "floor_mean_at_largest": _f(largest),
        "delta_largest_minus_smallest": _f(delta),
        "spearman_rho_size_vs_untrained_r2": _f(rho),
        "monotonic_nondecreasing_within_tolerance": bool(monotonic),
        "floor_rises_with_size": floor_rises_with_size,
        "interpretation": (
            "The untrained-reservoir floor RISES with n_hidden (delta>=0.05, rho>=0.5): the "
            "'place fell below the untrained floor' result at n_hidden=512 is AT LEAST PARTLY a "
            "capacity artifact — a bigger random reservoir decodes position better purely from "
            "richer untrained dynamics, independent of any learning."
            if floor_rises_with_size else
            "The untrained-reservoir floor does NOT rise materially with n_hidden (delta<0.05 or "
            "rho<0.5): the floor is roughly SIZE-INVARIANT over this range, so 'place fell below "
            "the untrained floor' is NOT explained by a capacity artifact — the floor is genuinely "
            "about the input statistics + a random recurrent projection, not the reservoir's raw size."
        ),
    }


# ─────────────────────────────────────────────────────────────────────────────
# main
# ─────────────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description="Does the untrained-reservoir place-decode floor rise with n_hidden?")
    ap.add_argument("--sizes", type=int, nargs="+", default=N_HIDDEN_SIZES_DEFAULT)
    ap.add_argument("--seeds", type=int, nargs="+", default=SEEDS_DEFAULT)
    ap.add_argument("--n-probe", type=int, default=N_PROBE_DEFAULT)
    ap.add_argument("--units", choices=["rate", "spike"], default="rate")
    ap.add_argument("--encoder", choices=["learned_ema", "fixed"], default="learned_ema")
    ap.add_argument("--n-train", type=int, default=N_TRAIN_DEFAULT)
    ap.add_argument("--train-contrast", dest="train_contrast", action="store_true", default=True,
                     help="also run the optional secondary trained-core contrast (default ON; cheap on CPU)")
    ap.add_argument("--no-train-contrast", dest="train_contrast", action="store_false",
                     help="skip the trained-core contrast; untrained-floor-vs-size curve only")
    ap.add_argument("--train-contrast-seeds", type=int, nargs="+", default=None,
                     help="subset of --seeds to run the (more expensive) train-contrast arm on "
                          "(default: all of --seeds)")
    ap.add_argument("--out", type=str, default=None)
    ap.add_argument("--smoke", action="store_true", help="tiny end-to-end self-test (seconds)")
    args = ap.parse_args()

    if args.smoke:
        args.sizes = [64, 128]
        args.seeds = [42]
        args.n_probe = 400
        args.n_train = 500
        args.train_contrast = True

    train_seeds = args.train_contrast_seeds if args.train_contrast_seeds else args.seeds

    t_start = time.time()
    per_size_seed = []
    trained_results = []
    for seed in args.seeds:
        wcfg = WorldConfig(seed=seed)
        input_seq, POS, RAW = collect_exploration_sequence(wcfg, args.n_probe, seed)
        print(f"[seed {seed}] captured {len(POS)}-step fixed exploration sequence "
              f"(grid={wcfg.grid_size}, n_v1={wcfg.n_v1})")
        for nh in args.sizes:
            res = untrained_floor_for_size(nh, seed, wcfg, input_seq, POS, RAW,
                                            units=args.units, encoder=args.encoder)
            per_size_seed.append(res)
            print(f"    n_hidden={nh:>5}  r2_untrained={res['r2_untrained']:+.4f}  "
                  f"r2_rawv1={res['r2_rawv1']:+.4f}  r2_shuffle={res['r2_shuffle']:+.4f}  "
                  f"({res['elapsed_s']}s)")

        if args.train_contrast and seed in train_seeds:
            for nh in args.sizes:
                tres = train_and_probe_for_size(nh, seed, wcfg, args.n_train, args.n_probe,
                                                 units=args.units, encoder=args.encoder)
                trained_results.append(tres)
                print(f"    [train-contrast] n_hidden={nh:>5}  r2_trained={tres['r2_trained']:+.4f}  "
                      f"r2_untrained(matched)={tres['r2_untrained_matched_probe']:+.4f}  "
                      f"advantage={tres['advantage_trained_minus_untrained']:+.4f}  "
                      f"(train {tres['train_elapsed_s']}s)")

    agg = aggregate_floor(per_size_seed, args.sizes)
    verdict = verdict_floor(per_size_seed, agg["curve"])

    trained_curve = None
    trained_verdict = None
    if trained_results:
        trained_curve = []
        for nh in args.sizes:
            rows = [r for r in trained_results if r["n_hidden"] == nh]
            if not rows:
                continue
            adv = [r["advantage_trained_minus_untrained"] for r in rows if r["advantage_trained_minus_untrained"] is not None]
            trained_curve.append({
                "n_hidden": nh, "n": len(rows),
                "r2_trained_mean": _f(np.mean([r["r2_trained"] for r in rows])),
                "r2_untrained_matched_mean": _f(np.mean([r["r2_untrained_matched_probe"] for r in rows])),
                "advantage_mean": _f(np.mean(adv)) if adv else None,
                "advantage_sd": _f(np.std(adv, ddof=1)) if len(adv) > 1 else (0.0 if adv else None),
            })
        advs = [c["advantage_mean"] for c in trained_curve if c["advantage_mean"] is not None]
        sizes_with_adv = [c["n_hidden"] for c in trained_curve if c["advantage_mean"] is not None]
        if len(advs) >= 2:
            rho_adv = _spearman(sizes_with_adv, advs)
            trained_verdict = {
                "advantage_at_smallest": advs[0], "advantage_at_largest": advs[-1],
                "delta_advantage_largest_minus_smallest": _f(advs[-1] - advs[0]),
                "spearman_rho_size_vs_advantage": _f(rho_adv),
                "advantage_shrinks_with_size": bool(advs[-1] < advs[0] - 0.05 or rho_adv <= -0.5),
            }

    payload = {
        "battery": "fork_pcs_floor_scaling",
        "question": "does the untrained-reservoir place-decode floor rise with n_hidden (core size)?",
        "units": args.units, "encoder": args.encoder,
        "sizes": args.sizes, "seeds": args.seeds, "n_probe": args.n_probe,
        "train_contrast_run": bool(trained_results), "n_train": args.n_train if trained_results else None,
        "train_contrast_seeds": train_seeds if trained_results else None,
        "per_size_seed_untrained_floor": per_size_seed,
        "aggregate_untrained_floor_curve": agg["curve"],
        "verdict": verdict,
        "per_size_seed_trained_contrast": trained_results if trained_results else None,
        "aggregate_trained_contrast_curve": trained_curve,
        "trained_contrast_verdict": trained_verdict,
        "elapsed_total_s": round(time.time() - t_start, 1),
    }

    print("\n=== UNTRAINED-FLOOR-vs-SIZE CURVE (mean +/- sd over seeds) ===")
    print(f"{'n_hidden':>8} {'r2_untrained':>14} {'sd':>8} {'r2_rawv1':>10} {'r2_shuffle':>11}")
    for c in agg["curve"]:
        print(f"{c['n_hidden']:>8} {c['r2_untrained_mean']!s:>14} {c['r2_untrained_sd']!s:>8} "
              f"{c['r2_rawv1_mean']!s:>10} {c['r2_shuffle_mean']!s:>11}")
    print("\n=== VERDICT ===")
    print(json.dumps(verdict, indent=2))
    if trained_curve:
        print("\n=== TRAINED-CORE CONTRAST (mean over seeds) ===")
        print(f"{'n_hidden':>8} {'r2_trained':>12} {'r2_untr(matched)':>18} {'advantage':>11}")
        for c in trained_curve:
            print(f"{c['n_hidden']:>8} {c['r2_trained_mean']!s:>12} {c['r2_untrained_matched_mean']!s:>18} "
                  f"{c['advantage_mean']!s:>11}")
        if trained_verdict:
            print(json.dumps(trained_verdict, indent=2))

    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w") as fh:
            json.dump(payload, fh, indent=2)
        print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
