"""GAP#4 cheap-first de-risk: BTSP plateau-gated ONE-SHOT credit, and the BISTABLE plateau is what makes it
BEHAVIORAL-TIMESCALE (seconds), not spike-timing (ms).

Per the gap#4 pivot (finding 2026-07-18-gap4-onbridge-BDSP-coupling-REVIVED...): deep supervised BDSP-FA credit is a
confirmed depth-fragile boundary (rate ceiling ~0.715), AND the 2025 BTSP-credit preprint (biorxiv 2025.06.12.659336)
finds generalized BTSP ALSO gets harder with depth. So gap#4's real target (per the EMERGENCE BAR: the brain does NOT
do deep backprop) is a LOCAL, plateau-gated rule that lets the substrate LEARN one-shot -- BTSP in its ROBUST native
regime (Bittner-Magee 2017; Milstein-Magee 2021). The gap#5 bistable dendritic plateau I just built (self-regen SUSTAIN
+ KIR down-state) is precisely its enabling mechanism: a HELD plateau is a seconds-long INSTRUCTIVE signal, so a
presynaptic input active seconds before/after the plateau still overlaps it -> potentiates one-shot (behavioral
timescale). A TRANSIENT plateau (self_regen=0) only overlaps near-coincident inputs -> a narrow ms window (spike-timing).

THE MECHANISM (faithful, local, no weight transport, no global loss, ONE-SHOT):
  - IS(t) = the postsynaptic dendritic PLATEAU voltage above v_hold -- generated by the REAL bistable single-cell
    dynamics (fused_coincidence_plateau's self-limiting self-regen SUSTAIN + the KIR down-state; the exact terms the
    sim/ keystone edit added). Held (self_regen>0) => a seconds-long latch; transient (self_regen=0) => a ms blip.
  - E_i(t) = presynaptic synaptic-eligibility trace laid down when input i is active (tau_elig ~ seconds; Milstein).
  - BTSP update (one presentation): dw_i = eta * [ integral_t E_i(t)*IS(t) dt ] * (w_max - w_i)  (saturating potentiation).
    Local: each dw_i uses only its OWN pre-trace and the shared postsynaptic plateau. No W in the credit -> no transport.

ARMS / anti-cheats (identical inputs; only the labelled variable differs):
  - held vs transient plateau: the BEHAVIORAL-TIMESCALE window. GO: with the HELD plateau an input active +-tau_far
    (~1 s) from the plateau still potentiates (w rises >= pot_bar); with the TRANSIENT plateau that SAME far input does
    NOT (w ~ unchanged). => the bistable plateau is LOAD-BEARING for behavioral-timescale one-shot binding.
  - no-plateau (IS=0, the gate lesion): NO input potentiates (the plateau is the instructive gate) -> the moat.
  - never-active input (no eligibility): does NOT potentiate even with the plateau (needs the pre-trace).
  - one-shot: a SINGLE plateau presentation suffices (no repeated epochs).

GO (all must hold, 6 seeds): held_far_pot >= 0.5 AND held_far_pot > transient_far_pot + 0.3 (bistability load-bearing);
near input potentiates in BOTH (sanity); no-plateau -> all w ~ unchanged (moat, max dw <= 0.05); never-active -> ~unchanged.
Reuse-by-import (fused_coincidence_plateau); NO sim/ edit; CPU/numpy. Run: python -m research.runners._gap4_btsp_plateau_gated_derisk --seeds 42 43 44 100 101 102
"""
from __future__ import annotations
import argparse, json, os, sys, time, traceback
from pathlib import Path

os.environ.setdefault("SIM_BACKEND", "numpy")
_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))
import numpy as np  # noqa: E402
from sim.kernels import fused_coincidence_plateau  # noqa: E402 -- the exact keystone kernel (self-regen sustain)

OUT = _REPO / "research" / "findings" / "raw" / "_gap4_btsp_plateau_gated.json"
ER = -65.0


def plateau_trace(self_regen, kir_g, cue_c=8.0, cue_depol=40.0, cue_steps=40, total_steps=2000,
                  k_thresh=6.0, plateau_strength=4.0, gain=2.0, mg=1.0, tau=15.0, R=0.15, dt=1.0,
                  v_hold=-35.0, v_hold_k=0.2, kir_ek=-90.0, kir_vhalf=-50.0, kir_k=8.0, n_sub=8):
    """The REAL bistable single-cell apical dynamics (== the sim/ keystone terms). Returns v_apical(t) over total_steps.
    A coincident cue for cue_steps triggers the plateau; self_regen>0 LATCHES it (held), self_regen=0 DECAYS it (transient)."""
    decay = float(np.exp(-dt / 80.0)); decay_rise = float(np.exp(-dt / 2.0))
    g = np.array([0.0]); g_rise = np.array([0.0]); v = np.array([ER]); sdt = dt / n_sub
    tr = np.empty(total_steps)
    for t in range(total_steps):
        c = np.array([cue_c if t < cue_steps else 0.0])
        g, g_rise, I = fused_coincidence_plateau(g, g_rise, decay, decay_rise, v, 0.0, mg,
                                                 c, k_thresh, gain, plateau_strength, self_regen, v_hold, v_hold_k)
        depol = cue_depol if t < cue_steps else 0.0
        for _ in range(n_sub):
            dv = -(v - ER) + R * I + depol
            if kir_g != 0.0:
                dv = dv + (kir_g / (1.0 + np.exp((v - kir_vhalf) / kir_k))) * (kir_ek - v)
            v = np.clip(v + (sdt / tau) * dv, -90.0, 5.0)
        tr[t] = float(v[0])
    return tr


def elig_trace(t_active, total_steps, width=60, tau_elig=400.0):
    """Presynaptic synaptic-eligibility trace: a brief activation at t_active leaves a seconds-long decaying trace
    (Milstein: the pre-side eligibility of BTSP is ~seconds). Rises during the activation, decays with tau_elig after."""
    E = np.zeros(total_steps)
    dec = float(np.exp(-1.0 / tau_elig))
    val = 0.0
    for t in range(total_steps):
        if t_active <= t < t_active + width:
            val = min(1.0, val + 0.05)          # ramp up during activation
        else:
            val = val * dec                      # decay after
        E[t] = val
    return E


def btsp_dw(E, IS, w0, eta=0.004, w_max=1.0, is_thresh=None):
    """One-shot BTSP: dw = eta * integral_t E(t)*IS_pos(t) dt * (w_max - w0). IS_pos = plateau voltage above v_hold."""
    if is_thresh is None:
        is_thresh = -35.0
    IS_pos = np.maximum(IS - is_thresh, 0.0)     # instructive signal = plateau depolarization above v_hold
    overlap = float(np.sum(E * IS_pos))
    return eta * overlap * (w_max - w0)


def run(seed):
    rng = np.random.default_rng(seed)
    T = 2000
    # The plateau is TRIGGERED by a coincident cue over t=0..40 (cue_steps). A HELD plateau (self_regen>0) then LATCHES
    # and stays up for seconds; a TRANSIENT plateau (self_regen=0) decays back within ~10-20 ms of the cue ending.
    IS_held = plateau_trace(self_regen=2.0, kir_g=1.0, total_steps=T)
    IS_tran = plateau_trace(self_regen=0.0, kir_g=1.0, total_steps=T)
    # tiny seed-jitter on the pre-activation times so seeds genuinely differ (dynamics are otherwise deterministic)
    j = int(rng.integers(0, 15))
    t_near = 5 + j                                 # CO-ACTIVE with the plateau trigger (within the transient's ms window)
    t_far = 900 + j                                # ~0.9 s AFTER the trigger (behavioral timescale; only a HELD plateau reaches it)
    E_near = elig_trace(max(0, t_near), T)
    E_far = elig_trace(max(0, t_far), T)
    w0 = 0.2

    def pot(E, IS):
        return btsp_dw(E, IS, w0)

    res = {
        "held_near": pot(E_near, IS_held), "held_far": pot(E_far, IS_held),
        "transient_near": pot(E_near, IS_tran), "transient_far": pot(E_far, IS_tran),
        "held_noplateau": pot(E_near, np.full(T, ER)),          # gate lesion: IS held at rest -> no instructive signal
        "held_neveractive": pot(np.zeros(T), IS_held),          # no eligibility -> no potentiation
        "IS_held_hold": float(np.mean(IS_held[-300:])),         # the latch holds (sanity)
        "IS_tran_hold": float(np.mean(IS_tran[-300:])),         # the transient decayed (sanity)
    }
    return {"seed": seed, **res}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", type=int, nargs="+", default=[42, 43, 44, 100, 101, 102])
    ap.add_argument("--out", default=str(OUT))
    a = ap.parse_args()
    if len(a.seeds) < 3:
        print("NOT-RUNNABLE: need >=3 seeds"); return 2
    t0 = time.time(); err = None; per = []
    try:
        for s in a.seeds:
            r = run(s); per.append(r)
            print(f"  [seed {s}] held(near {r['held_near']:.3f} far {r['held_far']:.3f}) | "
                  f"transient(near {r['transient_near']:.3f} far {r['transient_far']:.3f}) | "
                  f"no-plateau {r['held_noplateau']:.4f} | never-active {r['held_neveractive']:.4f} | "
                  f"IS_hold held {r['IS_held_hold']:.1f} tran {r['IS_tran_hold']:.1f}", flush=True)
    except Exception as e:
        err = repr(e); traceback.print_exc()

    if err is None:
        def mean(k):
            return float(np.mean([p[k] for p in per]))
        hn, hf = mean("held_near"), mean("held_far")
        tn, tf = mean("transient_near"), mean("transient_far")
        nop, nev = mean("held_noplateau"), mean("held_neveractive")
        pot_bar = 0.5 * hn                                       # "potentiated" = >= half the near-coincident potentiation
        # per-seed gates (robustness)
        far_holds = all(p["held_far"] >= 0.5 * p["held_near"] for p in per)
        bistable_loadbearing = all(p["held_far"] > p["transient_far"] + 0.5 * p["held_near"] for p in per)
        near_both = all(p["held_near"] > 0 and p["transient_near"] > 0 for p in per)
        moat = all(p["held_noplateau"] <= 0.05 * p["held_near"] and p["held_neveractive"] <= 0.05 * p["held_near"]
                   for p in per)
        latch_ok = all(p["IS_held_hold"] > -50.0 and p["IS_tran_hold"] < -55.0 for p in per)
        go = bool(far_holds and bistable_loadbearing and near_both and moat and latch_ok)
        if go:
            verdict = (f"GO -- BTSP plateau-gated ONE-SHOT credit works AND the BISTABLE plateau is load-bearing for the "
                       f"BEHAVIORAL-TIMESCALE (seconds) window. A pre-input ~0.9 s AFTER the plateau potentiates with the "
                       f"HELD plateau (far {hf:.3f} vs near {hn:.3f}) but NOT with the TRANSIENT plateau (far {tf:.3f}) -- "
                       f"the seconds-long latch (== the gap#5 keystone terms) extends the credit window from ms to "
                       f"seconds. Gate-lesion no-plateau ~0 ({nop:.4f}); never-active ~0 ({nev:.4f}) = the moat. One-shot "
                       f"(single plateau). Local, no weight transport, no global loss. 6-seed. => gap#4's local plateau-"
                       f"gated credit rule WORKS in BTSP's robust regime; the bistable dendritic plateau IS the enabler.")
        else:
            miss = []
            if not far_holds: miss.append(f"held-far didn't potentiate (far {hf:.3f} vs near {hn:.3f})")
            if not bistable_loadbearing: miss.append(f"bistability not load-bearing (held-far {hf:.3f} vs transient-far {tf:.3f})")
            if not near_both: miss.append("near input didn't potentiate in both")
            if not moat: miss.append(f"moat leak (no-plateau {nop:.4f} / never-active {nev:.4f})")
            if not latch_ok: miss.append("plateau latch/transient sanity failed")
            verdict = ("BOUNDARY -- " + "; ".join(miss) + ". Per THE LAW: iterate the plateau/eligibility timescales or "
                       "the BTSP rule form (Milstein saturating bidirectional), NOT a stop.")
    else:
        go = False; verdict = f"ERROR -- {err}"

    summary = {"probe": "gap4_btsp_plateau_gated", "GO": go, "verdict": verdict,
               "mechanism": "BTSP one-shot plateau-gated credit (Bittner-Magee 2017 / Milstein-Magee 2021): dw = eta * "
                            "integral E_pre(t)*IS_plateau(t) dt * (w_max-w); IS = the REAL bistable apical plateau (gap#5 "
                            "keystone terms). Held plateau => seconds-long behavioral-timescale window; transient => ms.",
               "seeds": a.seeds, "elapsed_seconds": round(time.time() - t0, 1), "per_seed": per,
               "HONEST_NOTE": "Targets BTSP's ROBUST native regime (shallow, one-shot) -- the 2025 BTSP-credit preprint "
                              "(biorxiv 2025.06.12.659336) finds generalized BTSP ALSO gets harder with DEPTH, so this "
                              "does NOT claim deep multi-layer credit; it claims a working LOCAL plateau-gated rule on the "
                              "bistable substrate (the EMERGENCE-BAR-aligned gap#4 target)."}
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text(json.dumps(summary, indent=2, default=str))
    print("\n" + "=" * 100, flush=True)
    print(f"[gap4-btsp] VERDICT: {verdict}", flush=True)
    print(f"[gap4-btsp] wrote {a.out}\n" + "=" * 100, flush=True)
    return 0 if go else 1


if __name__ == "__main__":
    sys.exit(main())
