"""Regenerate the develop-loop's high-freq-first curriculum VOCAB npz from the corpus + facts.

WHY THIS EXISTS (2026-07-17). The corpus-curriculum develop loop
(`research.runners._corpus_develop_curriculum.load_concepts_and_facts`) reads ONLY `d["vocab"]`
from its `--brain` npz -- a high-frequency-first list of concept words that orders the day-by-day
syllabus. The StreamCortex then LEARNS every concept's code fresh from the corpus; nothing else in
the npz is used on the corpus-curriculum path (confirmed: `_corpus_develop_curriculum.py:99-100`).

The original ordering artifact (`bridges/firstchat/brain3000pos_w7000.npz_seed42.npz`) was an
untracked file lost when the E: drive was wiped (Linux migration, 2026-07-16). Because the npz is
ONLY a vocab-ordering source, it is regenerable directly from the two committed inputs -- the
corpus and the SVO facts file -- with clean provenance, instead of retraining a 3000-concept brain.

The concepts are the union of {agent, action, patient} across the facts (the words the curriculum
actually teaches), ordered high-frequency-first by their count in the corpus (the same
"high-frequency-first" ordering the original curriculum trainer used). Deterministic: same
inputs -> byte-identical vocab order (frequency desc, ties broken alphabetically -- NOT by dict
insertion, so it does not depend on Python's set/dict ordering).

Usage:
    python -m research.runners._regen_curriculum_vocab \
        --facts-json research/findings/raw/_facts3000.json \
        --corpus data/corpus/tinystories.txt \
        --out bridges/firstchat/brain_curriculum_vocab_regen.npz

Then feed it to the develop loop:
    SIM_BACKEND=cupy python -m research.runners.develop_run --corpus-curriculum \
        --brain bridges/firstchat/brain_curriculum_vocab_regen.npz ...
"""

import argparse
import json
import os
import re
import sys
from collections import Counter

import numpy as np


def _concepts_from_facts(facts_json):
    raw = json.load(open(facts_json, encoding="utf-8"))
    items = raw["facts"] if isinstance(raw, dict) and "facts" in raw else raw
    concepts = set()
    for f in items:
        if isinstance(f, dict):
            trip = (f.get("agent") or f.get("subject") or f.get("s"),
                    f.get("action") or f.get("verb") or f.get("v"),
                    f.get("patient") or f.get("object") or f.get("o"))
        elif isinstance(f, (list, tuple)) and len(f) >= 3:
            trip = (f[0], f[1], f[2])
        else:
            continue
        for w in trip:
            if w:
                concepts.add(str(w).strip().lower())
    return concepts, len(items)


def _corpus_word_counts(corpus_path):
    """Case-insensitive word-token frequency over the whole corpus."""
    counts = Counter()
    tok = re.compile(r"[a-z]+")
    with open(corpus_path, encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            counts.update(tok.findall(line.lower()))
    return counts


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--facts-json", default="research/findings/raw/_facts3000.json")
    ap.add_argument("--corpus", default="data/corpus/tinystories.txt")
    ap.add_argument("--out", default="bridges/firstchat/brain_curriculum_vocab_regen.npz")
    ap.add_argument("--min-corpus-count", type=int, default=1,
                    help="drop concepts appearing fewer than this many times in the corpus "
                         "(the StreamCortex cannot learn a code for a word it never hears)")
    a = ap.parse_args()

    concepts, n_facts = _concepts_from_facts(a.facts_json)
    counts = _corpus_word_counts(a.corpus)

    # high-frequency-first; a concept the corpus never contains cannot be learned, so drop it.
    ranked = sorted(
        (w for w in concepts if counts.get(w, 0) >= a.min_corpus_count),
        key=lambda w: (-counts.get(w, 0), w),   # freq desc, then alpha -> deterministic ties
    )
    dropped = sorted(w for w in concepts if counts.get(w, 0) < a.min_corpus_count)

    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    vocab = np.array(ranked, dtype=object)
    np.savez(
        a.out,
        vocab=vocab,
        provenance=np.array(
            [f"regenerated by _regen_curriculum_vocab from {a.facts_json} + {a.corpus}; "
             f"union of SVO concepts, high-freq-first; replaces E:-wiped brain3000pos_w7000"],
            dtype=object),
    )

    print(f"[regen-vocab] {n_facts} facts -> {len(concepts)} unique concepts; "
          f"{len(ranked)} kept (corpus-count >= {a.min_corpus_count}), {len(dropped)} dropped")
    if dropped:
        print(f"[regen-vocab]   dropped (not in corpus): {dropped[:12]}"
              f"{' ...' if len(dropped) > 12 else ''}")
    print(f"[regen-vocab] top-15 (high-freq-first): "
          f"{[(w, counts.get(w, 0)) for w in ranked[:15]]}")
    print(f"[regen-vocab] saved -> {a.out}")

    # verify the artifact round-trips exactly as the develop loop will read it
    d = np.load(a.out, allow_pickle=True)
    got = [str(w) for w in d["vocab"]]
    assert got == ranked, "round-trip mismatch: saved vocab != read vocab"
    print(f"[regen-vocab] round-trip OK: {len(got)} concepts read back identical")
    return 0


if __name__ == "__main__":
    sys.exit(main())
