#!/usr/bin/env python3
"""Apply a --parent-status-archive JSON to an ALREADY-GENERATED tools/audit_pool_fragment_claims.py report, in
place, using the exact same matching logic that flag uses inside main() (claim_line, tuple(parent_outputs),
occurrence_src, occurrence_line, occurrence_time -- never job_b64, which the archive does not carry).

WHY THIS EXISTS SEPARATELY FROM RE-RUNNING THE AUDIT TOOL (fix round r3, review MEDIUM item, 2026-09-25): the
straightforward fix -- re-run audit_pool_fragment_claims.py with --parent-status-archive against the live queue --
requires research/queue/{pool.queue.claims,pool.running,dispatch.log}, which a worktree-isolated fix-round agent
does not have (out of scope: never touch research/queue/* or any live service). This script instead patches the
report JSON a run WITH live access already produced (research/findings/raw/_dispatcher_fragment_audit/
2026-09-25-fragments.json, git_sha c2440fcb2, generated by fix round r2), filling only the parent occurrences that
run left unresolved (it never fetched job_status for PARENT full-line reruns, only for the fragments/A2 lines
themselves -- see that report's own provenance and the finding's Method section). It never touches a fragment's
own node_status, never overrides an occurrence that already has one, and records exactly what it did in a new
`report["restorations"]` list so the change is as auditable as any other provenance-gated artifact here.

    .venv/bin/python tools/apply_parent_status_archive.py --report <fragments.json> --archive <archive.json>
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_archive(path):
    data = json.load(open(path))
    out = {}
    for e in data["entries"]:
        key = (e["claim_line"], tuple(e["parent_outputs"]), e["occurrence_src"], e["occurrence_line"],
               e.get("occurrence_time"))
        out[key] = e["node_status"]
    return out


def apply_archive(report, archive, archive_tag):
    """Mutates `report` in place. Returns (filled, already_live, no_match)."""
    filled = already_live = no_match = 0
    for f in report.get("fragments", []):
        cl = f["claim_line"]
        for p in f.get("parents", []):
            outputs = tuple(p["outputs"])
            for o in p.get("occurrences_at_or_after_fragment", []):
                if o.get("node_status"):
                    already_live += 1
                    continue
                key = (cl, outputs, o["src"], o["line"], o.get("time"))
                hit = archive.get(key)
                if hit:
                    o["node_status"] = hit
                    o["node_status_source"] = "archive:%s" % archive_tag
                    filled += 1
                else:
                    no_match += 1
    return filled, already_live, no_match


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--report", required=True, help="tools/audit_pool_fragment_claims.py --json output to patch, in place")
    ap.add_argument("--archive", required=True, help="a --parent-status-archive JSON (see load_parent_status_archive)")
    a = ap.parse_args()

    report = json.load(open(a.report))
    archive_tag = os.path.relpath(os.path.abspath(a.archive), REPO)
    archive = load_archive(a.archive)
    filled, already_live, no_match = apply_archive(report, archive, archive_tag)

    report.setdefault("restorations", []).append({
        "script": "tools/apply_parent_status_archive.py",
        "archive": archive_tag,
        "git_sha": subprocess.run(["git", "-C", REPO, "rev-parse", "HEAD"], capture_output=True,
                                  text=True).stdout.strip(),
        "applied": dt.datetime.now().isoformat(timespec="seconds"),
        "filled": filled, "already_live": already_live, "no_match": no_match,
        "reason": "this worktree has no research/queue/ access to re-run the audit tool end to end; see this "
                  "script's own docstring",
    })
    json.dump(report, open(a.report, "w"), indent=1)
    print("filled=%d already_live=%d no_match=%d -> %s" % (filled, already_live, no_match, a.report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
