"""Direction 8 vocab spec - 5 categories x V=128 = 640 cross-bridge concepts.

Pre-registered FROZEN word lists. This is the 2x-vocab extension of
Direction 7 (5 categories x V=64 = 320 cross-bridge concepts) per the
pillar D7 G.20-matched per-category result, scaling to V=128 per bridge x
5 bridges = 640 cross-bridge concepts.

The first 64 words per category are taken BYTE-FOR-BYTE from the
Direction 7 V=64 spec (which in turn mirrors the Direction M G.20 sparse
production deliverable vocab64). D8 is therefore a strict SUPERSET of
D7 -- the same 320 concepts in identical order, plus 64 additional
words per category that extend the vocabulary to 128 per bridge.
This makes D8 the next-tier stress test of bio_brain_regions cross-bridge
composition at 2x the G.20 production vocab.

Each list maps to ONE separate bio_brain_regions bridge:
- BridgeA (nouns, 128 words):       D7 64 nouns + 64 new (animals, body, food, places)
- BridgeB (verbs, 128 words):       D7 64 verbs + 64 new (action, perception, communication, emotion)
- BridgeC (adjectives, 128 words):  D7 64 adj + 64 new (sensory, emotional, size/shape, colors)
- BridgeD (spatial, 128 words):     D7 64 spatial + 64 new (directional, temporal, relational, measurement)
- BridgeE (functional, 128 words):  D7 64 functional + 64 new (pronouns, wh-words, discourse, auxiliaries)

TOTAL: 640 unique cross-bridge concepts.

Architectural notes (per implementation plan; same as D4 / D6 / D7):
- BridgeA / B / C load their vocab into the matching pool kind
  (noun_pool_names / verb_pool_names / adjective_pool_names).
- BridgeD (spatial) and BridgeE (functional) load their vocab into the
  noun_pool_names slot - the protected builder has no dedicated spatial
  or functional pool kind, but the concept-pool architecture is category-
  agnostic at the pool level (each pool is a 200-neuron concept attractor
  with FS interneurons + lang_input/lang_output pathways). This preserves
  build_biological_brain_regions byte-unchanged.

Predicted via FHRR algebra capacity ratio (capacity proportional to
N_dim/V): D7 V=320 was the G.20 production-tier match. D8 V=640 is the
next-tier stress test: if D8 also passes the moderate loads {2, 3, 5},
biology-faithful dedicated-pool architecture scales beyond the Direction
M G.20 sparse production deliverable -- the conversational-capability
post-production tier.

DISCIPLINE: this module is data only (no imports beyond typing). The
words are FROZEN as module-level constants; no runtime override path.
Any PR that silently changes a word triggers the grounding-pin test
test_direction_8_vocab_spec_has_5_categories_v128_each in
tests/test_direction_8_grounding.py.
"""
from __future__ import annotations
from typing import Dict, List


# -----------------------------------------------------------------------
# Pre-registered 5-category V=128 vocab lists (frozen at module load).
# The first 64 entries per list mirror Direction 7 byte-for-byte (which
# in turn mirrors the G.20 320-concept production deliverable vocab64).
# The next 64 entries per list extend the vocabulary uniquely.
# NO duplicates across the 5 categories.
# -----------------------------------------------------------------------

# Bridge A - nouns (128). First 64 mirror g20_bridgeA_nouns_vocab64.txt.
DIRECTION_8_NOUN_VOCAB: Dict[str, str] = {
    # ----- D7 64 nouns (byte-identical) -----
    "apple": "APPLE",
    "river": "RIVER",
    "dog": "DOG",
    "cat": "CAT",
    "bird": "BIRD",
    "fish": "FISH",
    "mouse": "MOUSE",
    "frog": "FROG",
    "tree": "TREE",
    "flower": "FLOWER",
    "leaf": "LEAF",
    "fruit": "FRUIT",
    "ball": "BALL",
    "key": "KEY",
    "book": "BOOK",
    "cup": "CUP",
    "hand": "HAND",
    "foot": "FOOT",
    "head": "HEAD",
    "eye": "EYE",
    "person": "PERSON",
    "baby": "BABY",
    "child": "CHILD",
    "friend": "FRIEND",
    "house": "HOUSE",
    "road": "ROAD",
    "garden": "GARDEN",
    "park": "PARK",
    "water": "WATER",
    "fire": "FIRE",
    "sun": "SUN",
    "moon": "MOON",
    "horse": "HORSE",
    "cow": "COW",
    "pig": "PIG",
    "sheep": "SHEEP",
    "duck": "DUCK",
    "bee": "BEE",
    "ant": "ANT",
    "snake": "SNAKE",
    "bear": "BEAR",
    "wolf": "WOLF",
    "grass": "GRASS",
    "seed": "SEED",
    "root": "ROOT",
    "branch": "BRANCH",
    "box": "BOX",
    "bag": "BAG",
    "spoon": "SPOON",
    "plate": "PLATE",
    "chair": "CHAIR",
    "table": "TABLE",
    "bed": "BED",
    "door": "DOOR",
    "window": "WINDOW",
    "arm": "ARM",
    "leg": "LEG",
    "ear": "EAR",
    "nose": "NOSE",
    "mouth": "MOUTH",
    "mother": "MOTHER",
    "father": "FATHER",
    "school": "SCHOOL",
    "shop": "SHOP",
    # ----- D8 +64 new nouns -----
    # Animals (16)
    "lion": "LION",
    "tiger": "TIGER",
    "elephant": "ELEPHANT",
    "monkey": "MONKEY",
    "giraffe": "GIRAFFE",
    "rabbit": "RABBIT",
    "deer": "DEER",
    "fox": "FOX",
    "goat": "GOAT",
    "chicken": "CHICKEN",
    "owl": "OWL",
    "eagle": "EAGLE",
    "shark": "SHARK",
    "whale": "WHALE",
    "turtle": "TURTLE",
    "spider": "SPIDER",
    # Body parts (16)
    "finger": "FINGER",
    "knee": "KNEE",
    "hair": "HAIR",
    "brain": "BRAIN",
    "heart": "HEART",
    "tooth": "TOOTH",
    "tongue": "TONGUE",
    "neck": "NECK",
    "shoulder": "SHOULDER",
    "elbow": "ELBOW",
    "wrist": "WRIST",
    "ankle": "ANKLE",
    "toe": "TOE",
    "lip": "LIP",
    "chin": "CHIN",
    "cheek": "CHEEK",
    # Foods (16)
    "rice": "RICE",
    "soup": "SOUP",
    "cheese": "CHEESE",
    "sugar": "SUGAR",
    "honey": "HONEY",
    "tea": "TEA",
    "bread": "BREAD",
    "butter": "BUTTER",
    "egg": "EGG",
    "milk": "MILK",
    "salt": "SALT",
    "meat": "MEAT",
    "cake": "CAKE",
    "candy": "CANDY",
    "juice": "JUICE",
    "coffee": "COFFEE",
    # Places (16)
    "city": "CITY",
    "town": "TOWN",
    "beach": "BEACH",
    "forest": "FOREST",
    "lake": "LAKE",
    "mountain": "MOUNTAIN",
    "field": "FIELD",
    "farm": "FARM",
    "store": "STORE",
    "office": "OFFICE",
    "hospital": "HOSPITAL",
    "church": "CHURCH",
    "kitchen": "KITCHEN",
    "bathroom": "BATHROOM",
    "yard": "YARD",
    "valley": "VALLEY",
}

# Bridge B - verbs (128). First 64 mirror g20_bridgeB_verbs_vocab64.txt.
DIRECTION_8_VERB_VOCAB: Dict[str, str] = {
    # ----- D7 64 verbs (byte-identical) -----
    "go": "GO",
    "come": "COME",
    "run": "RUN",
    "walk": "WALK",
    "jump": "JUMP",
    "fall": "FALL",
    "fly": "FLY",
    "swim": "SWIM",
    "look": "LOOK",
    "see": "SEE",
    "hear": "HEAR",
    "listen": "LISTEN",
    "watch": "WATCH",
    "find": "FIND",
    "push": "PUSH",
    "pull": "PULL",
    "open": "OPEN",
    "close": "CLOSE",
    "give": "GIVE",
    "take": "TAKE",
    "hold": "HOLD",
    "drop": "DROP",
    "speak": "SPEAK",
    "read": "READ",
    "write": "WRITE",
    "say": "SAY",
    "eat": "EAT",
    "drink": "DRINK",
    "sleep": "SLEEP",
    "wake": "WAKE",
    "stop": "STOP",
    "wait": "WAIT",
    "sit": "SIT",
    "stand": "STAND",
    "turn": "TURN",
    "climb": "CLIMB",
    "crawl": "CRAWL",
    "ride": "RIDE",
    "throw": "THROW",
    "catch": "CATCH",
    "kick": "KICK",
    "hit": "HIT",
    "touch": "TOUCH",
    "smell": "SMELL",
    "taste": "TASTE",
    "feel": "FEEL",
    "cut": "CUT",
    "break": "BREAK",
    "build": "BUILD",
    "make": "MAKE",
    "fix": "FIX",
    "carry": "CARRY",
    "bring": "BRING",
    "send": "SEND",
    "ask": "ASK",
    "tell": "TELL",
    "call": "CALL",
    "answer": "ANSWER",
    "cook": "COOK",
    "wash": "WASH",
    "laugh": "LAUGH",
    "cry": "CRY",
    "play": "PLAY",
    "work": "WORK",
    # ----- D8 +64 new verbs -----
    # Action (16)
    "skip": "SKIP",
    "dance": "DANCE",
    "sing": "SING",
    "paint": "PAINT",
    "draw": "DRAW",
    "bake": "BAKE",
    "scrub": "SCRUB",
    "sweep": "SWEEP",
    "pour": "POUR",
    "lift": "LIFT",
    "drag": "DRAG",
    "spin": "SPIN",
    "roll": "ROLL",
    "bounce": "BOUNCE",
    "slide": "SLIDE",
    "stretch": "STRETCH",
    # Perception (16)
    "peer": "PEER",
    "notice": "NOTICE",
    "stare": "STARE",
    "glance": "GLANCE",
    "observe": "OBSERVE",
    "spot": "SPOT",
    "examine": "EXAMINE",
    "inspect": "INSPECT",
    "sniff": "SNIFF",
    "lick": "LICK",
    "chew": "CHEW",
    "swallow": "SWALLOW",
    "blink": "BLINK",
    "wink": "WINK",
    "yawn": "YAWN",
    "sneeze": "SNEEZE",
    # Communication (16)
    "whisper": "WHISPER",
    "shout": "SHOUT",
    "greet": "GREET",
    "argue": "ARGUE",
    "agree": "AGREE",
    "explain": "EXPLAIN",
    "describe": "DESCRIBE",
    "promise": "PROMISE",
    "warn": "WARN",
    "thank": "THANK",
    "apologize": "APOLOGIZE",
    "boast": "BOAST",
    "joke": "JOKE",
    "yell": "YELL",
    "mumble": "MUMBLE",
    "chat": "CHAT",
    # Emotion (16)
    "love": "LOVE",
    "hate": "HATE",
    "fear": "FEAR",
    "hope": "HOPE",
    "trust": "TRUST",
    "worry": "WORRY",
    "smile": "SMILE",
    "frown": "FROWN",
    "enjoy": "ENJOY",
    "dislike": "DISLIKE",
    "miss": "MISS",
    "wish": "WISH",
    "dream": "DREAM",
    "regret": "REGRET",
    "celebrate": "CELEBRATE",
    "panic": "PANIC",
}

# Bridge C - adjectives (128). First 64 mirror g20_bridgeC_adj_vocab64.txt.
DIRECTION_8_ADJECTIVE_VOCAB: Dict[str, str] = {
    # ----- D7 64 adjectives (byte-identical) -----
    "big": "BIG",
    "small": "SMALL",
    "tall": "TALL",
    "short": "SHORT",
    "long": "LONG",
    "wide": "WIDE",
    "hot": "HOT",
    "cold": "COLD",
    "warm": "WARM",
    "cool": "COOL",
    "fast": "FAST",
    "slow": "SLOW",
    "red": "RED",
    "blue": "BLUE",
    "green": "GREEN",
    "yellow": "YELLOW",
    "white": "WHITE",
    "black": "BLACK",
    "happy": "HAPPY",
    "sad": "SAD",
    "angry": "ANGRY",
    "scared": "SCARED",
    "new": "NEW",
    "old": "OLD",
    "clean": "CLEAN",
    "dirty": "DIRTY",
    "wet": "WET",
    "dry": "DRY",
    "hard": "HARD",
    "soft": "SOFT",
    "smooth": "SMOOTH",
    "full": "FULL",
    "huge": "HUGE",
    "tiny": "TINY",
    "thin": "THIN",
    "thick": "THICK",
    "deep": "DEEP",
    "narrow": "NARROW",
    "bright": "BRIGHT",
    "dark": "DARK",
    "loud": "LOUD",
    "quiet": "QUIET",
    "sweet": "SWEET",
    "sour": "SOUR",
    "heavy": "HEAVY",
    "light": "LIGHT",
    "strong": "STRONG",
    "weak": "WEAK",
    "rich": "RICH",
    "poor": "POOR",
    "kind": "KIND",
    "mean": "MEAN",
    "nice": "NICE",
    "good": "GOOD",
    "bad": "BAD",
    "empty": "EMPTY",
    "round": "ROUND",
    "flat": "FLAT",
    "sharp": "SHARP",
    "young": "YOUNG",
    "sick": "SICK",
    "well": "WELL",
    "true": "TRUE",
    "false": "FALSE",
    # ----- D8 +64 new adjectives -----
    # Sensory (16)
    "rough": "ROUGH",
    "salty": "SALTY",
    "bitter": "BITTER",
    "spicy": "SPICY",
    "fresh": "FRESH",
    "stale": "STALE",
    "sticky": "STICKY",
    "slippery": "SLIPPERY",
    "fuzzy": "FUZZY",
    "shiny": "SHINY",
    "dull": "DULL",
    "blurry": "BLURRY",
    "clear": "CLEAR",
    "noisy": "NOISY",
    "silent": "SILENT",
    "fragrant": "FRAGRANT",
    # Emotional (16)
    "calm": "CALM",
    "busy": "BUSY",
    "lazy": "LAZY",
    "brave": "BRAVE",
    "shy": "SHY",
    "proud": "PROUD",
    "jealous": "JEALOUS",
    "grumpy": "GRUMPY",
    "cheerful": "CHEERFUL",
    "tired": "TIRED",
    "excited": "EXCITED",
    "bored": "BORED",
    "confused": "CONFUSED",
    "curious": "CURIOUS",
    "lonely": "LONELY",
    "friendly": "FRIENDLY",
    # Size/shape (16)
    "oblong": "OBLONG",
    "linear": "LINEAR",
    "square": "SQUARE",
    "oval": "OVAL",
    "curved": "CURVED",
    "straight": "STRAIGHT",
    "bent": "BENT",
    "crooked": "CROOKED",
    "twisted": "TWISTED",
    "broad": "BROAD",
    "slim": "SLIM",
    "chubby": "CHUBBY",
    "plump": "PLUMP",
    "skinny": "SKINNY",
    "vast": "VAST",
    "compact": "COMPACT",
    # Colors (16)
    "purple": "PURPLE",
    "orange": "ORANGE",
    "pink": "PINK",
    "brown": "BROWN",
    "gray": "GRAY",
    "gold": "GOLD",
    "silver": "SILVER",
    "violet": "VIOLET",
    "crimson": "CRIMSON",
    "scarlet": "SCARLET",
    "navy": "NAVY",
    "beige": "BEIGE",
    "ivory": "IVORY",
    "maroon": "MAROON",
    "teal": "TEAL",
    "magenta": "MAGENTA",
}

# Bridge D - spatial words (128). First 64 mirror g20_bridgeD_spatial_vocab64.txt.
# Mapped via noun_pool_names slot in the protected builder (no dedicated
# spatial pool kind; concept-pool architecture is category-agnostic at
# the pool level).
DIRECTION_8_SPATIAL_VOCAB: Dict[str, str] = {
    # ----- D7 64 spatial (byte-identical) -----
    "north": "NORTH",
    "south": "SOUTH",
    "east": "EAST",
    "west": "WEST",
    "up": "UP",
    "down": "DOWN",
    "left": "LEFT",
    "right": "RIGHT",
    "here": "HERE",
    "there": "THERE",
    "near": "NEAR",
    "far": "FAR",
    "in": "IN",
    "out": "OUT",
    "on": "ON",
    "under": "UNDER",
    "above": "ABOVE",
    "below": "BELOW",
    "front": "FRONT",
    "back": "BACK",
    "top": "TOP",
    "bottom": "BOTTOM",
    "side": "SIDE",
    "middle": "MIDDLE",
    "now": "NOW",
    "then": "THEN",
    "before": "BEFORE",
    "after": "AFTER",
    "first": "FIRST",
    "last": "LAST",
    "next": "NEXT",
    "today": "TODAY",
    "inside": "INSIDE",
    "outside": "OUTSIDE",
    "between": "BETWEEN",
    "around": "AROUND",
    "through": "THROUGH",
    "across": "ACROSS",
    "along": "ALONG",
    "toward": "TOWARD",
    "away": "AWAY",
    "beside": "BESIDE",
    "behind": "BEHIND",
    "beyond": "BEYOND",
    "center": "CENTER",
    "edge": "EDGE",
    "corner": "CORNER",
    "forward": "FORWARD",
    "yesterday": "YESTERDAY",
    "tomorrow": "TOMORROW",
    "soon": "SOON",
    "late": "LATE",
    "early": "EARLY",
    "always": "ALWAYS",
    "never": "NEVER",
    "often": "OFTEN",
    "sometimes": "SOMETIMES",
    "once": "ONCE",
    "again": "AGAIN",
    "later": "LATER",
    "until": "UNTIL",
    "since": "SINCE",
    "during": "DURING",
    "whenever": "WHENEVER",
    # ----- D8 +64 new spatial -----
    # Directional (16)
    "northeast": "NORTHEAST",
    "northwest": "NORTHWEST",
    "southeast": "SOUTHEAST",
    "southwest": "SOUTHWEST",
    "upward": "UPWARD",
    "downward": "DOWNWARD",
    "leftward": "LEFTWARD",
    "rightward": "RIGHTWARD",
    "inward": "INWARD",
    "outward": "OUTWARD",
    "backward": "BACKWARD",
    "sideways": "SIDEWAYS",
    "uphill": "UPHILL",
    "downhill": "DOWNHILL",
    "upstream": "UPSTREAM",
    "downstream": "DOWNSTREAM",
    # Temporal (16)
    "eternal": "ETERNAL",
    "brief": "BRIEF",
    "instant": "INSTANT",
    "constant": "CONSTANT",
    "occasional": "OCCASIONAL",
    "frequent": "FREQUENT",
    "rare": "RARE",
    "ancient": "ANCIENT",
    "modern": "MODERN",
    "future": "FUTURE",
    "past": "PAST",
    "present": "PRESENT",
    "daily": "DAILY",
    "weekly": "WEEKLY",
    "monthly": "MONTHLY",
    "yearly": "YEARLY",
    # Relational (16)
    "against": "AGAINST",
    "among": "AMONG",
    "beneath": "BENEATH",
    "underneath": "UNDERNEATH",
    "atop": "ATOP",
    "amid": "AMID",
    "alongside": "ALONGSIDE",
    "opposite": "OPPOSITE",
    "facing": "FACING",
    "adjacent": "ADJACENT",
    "parallel": "PARALLEL",
    "perpendicular": "PERPENDICULAR",
    "diagonal": "DIAGONAL",
    "horizontal": "HORIZONTAL",
    "vertical": "VERTICAL",
    "central": "CENTRAL",
    # Measurement (16)
    "proximate": "PROXIMATE",
    "distant": "DISTANT",
    "remote": "REMOTE",
    "nearby": "NEARBY",
    "local": "LOCAL",
    "global": "GLOBAL",
    "internal": "INTERNAL",
    "external": "EXTERNAL",
    "shallow": "SHALLOW",
    "high": "HIGH",
    "low": "LOW",
    "lofty": "LOFTY",
    "panoramic": "PANORAMIC",
    "confined": "CONFINED",
    "boundary": "BOUNDARY",
    "perimeter": "PERIMETER",
}

# Bridge E - functional words (128). First 64 mirror g20_bridgeE_functional_vocab64.txt.
# Same noun_pool_names slot mapping rationale as Bridge D.
DIRECTION_8_FUNCTIONAL_VOCAB: Dict[str, str] = {
    # ----- D7 64 functional (byte-identical) -----
    "one": "ONE",
    "two": "TWO",
    "three": "THREE",
    "four": "FOUR",
    "five": "FIVE",
    "many": "MANY",
    "few": "FEW",
    "some": "SOME",
    "all": "ALL",
    "none": "NONE",
    "every": "EVERY",
    "any": "ANY",
    "what": "WHAT",
    "where": "WHERE",
    "when": "WHEN",
    "who": "WHO",
    "why": "WHY",
    "how": "HOW",
    "this": "THIS",
    "that": "THAT",
    "yes": "YES",
    "no": "NO",
    "please": "PLEASE",
    "thanks": "THANKS",
    "hello": "HELLO",
    "goodbye": "GOODBYE",
    "sorry": "SORRY",
    "ok": "OK",
    "is": "IS",
    "have": "HAVE",
    "want": "WANT",
    "need": "NEED",
    "six": "SIX",
    "seven": "SEVEN",
    "eight": "EIGHT",
    "nine": "NINE",
    "ten": "TEN",
    "zero": "ZERO",
    "half": "HALF",
    "both": "BOTH",
    "each": "EACH",
    "other": "OTHER",
    "another": "ANOTHER",
    "same": "SAME",
    "which": "WHICH",
    "whose": "WHOSE",
    "these": "THESE",
    "those": "THOSE",
    "it": "IT",
    "maybe": "MAYBE",
    "very": "VERY",
    "too": "TOO",
    "also": "ALSO",
    "only": "ONLY",
    "not": "NOT",
    "can": "CAN",
    "will": "WILL",
    "do": "DO",
    "did": "DID",
    "and": "AND",
    "or": "OR",
    "but": "BUT",
    "if": "IF",
    "because": "BECAUSE",
    # ----- D8 +64 new functional -----
    # Pronouns/quantifiers (16)
    "everyone": "EVERYONE",
    "anybody": "ANYBODY",
    "everybody": "EVERYBODY",
    "nobody": "NOBODY",
    "someone": "SOMEONE",
    "anyone": "ANYONE",
    "everything": "EVERYTHING",
    "anything": "ANYTHING",
    "something": "SOMETHING",
    "nothing": "NOTHING",
    "several": "SEVERAL",
    "various": "VARIOUS",
    "plenty": "PLENTY",
    "enough": "ENOUGH",
    "least": "LEAST",
    "most": "MOST",
    # Wh-words and variants (16)
    "whatever": "WHATEVER",
    "whoever": "WHOEVER",
    "whomever": "WHOMEVER",
    "whichever": "WHICHEVER",
    "wherever": "WHEREVER",
    "however": "HOWEVER",
    "whether": "WHETHER",
    "whither": "WHITHER",
    "whence": "WHENCE",
    "thus": "THUS",
    "hence": "HENCE",
    "therefore": "THEREFORE",
    "thereby": "THEREBY",
    "thereof": "THEREOF",
    "wherein": "WHEREIN",
    "whereupon": "WHEREUPON",
    # Discourse markers (16)
    "anyway": "ANYWAY",
    "besides": "BESIDES",
    "moreover": "MOREOVER",
    "furthermore": "FURTHERMORE",
    "nevertheless": "NEVERTHELESS",
    "nonetheless": "NONETHELESS",
    "meanwhile": "MEANWHILE",
    "indeed": "INDEED",
    "actually": "ACTUALLY",
    "really": "REALLY",
    "truly": "TRULY",
    "perhaps": "PERHAPS",
    "probably": "PROBABLY",
    "certainly": "CERTAINLY",
    "obviously": "OBVIOUSLY",
    "frankly": "FRANKLY",
    # Auxiliaries and modals (16)
    "could": "COULD",
    "would": "WOULD",
    "should": "SHOULD",
    "might": "MIGHT",
    "must": "MUST",
    "shall": "SHALL",
    "may": "MAY",
    "ought": "OUGHT",
    "was": "WAS",
    "were": "WERE",
    "been": "BEEN",
    "being": "BEING",
    "am": "AM",
    "are": "ARE",
    "does": "DOES",
    "having": "HAVING",
}


# -----------------------------------------------------------------------
# Derived helpers (also frozen; no runtime override path).
# -----------------------------------------------------------------------

# Pool-name lists in the order expected by build_biological_brain_regions
# (noun_pool_names / verb_pool_names / adjective_pool_names parameters).
DIRECTION_8_NOUN_NAMES: List[str] = list(DIRECTION_8_NOUN_VOCAB.values())
DIRECTION_8_VERB_NAMES: List[str] = list(DIRECTION_8_VERB_VOCAB.values())
DIRECTION_8_ADJECTIVE_NAMES: List[str] = list(DIRECTION_8_ADJECTIVE_VOCAB.values())
DIRECTION_8_SPATIAL_NAMES: List[str] = list(DIRECTION_8_SPATIAL_VOCAB.values())
DIRECTION_8_FUNCTIONAL_NAMES: List[str] = list(DIRECTION_8_FUNCTIONAL_VOCAB.values())

# Per-bridge word lists (the word-as-key order; used by training schedules
# + cross-bridge probe decoder that consumes the FROZEN word order).
DIRECTION_8_BRIDGE_A_WORDS: List[str] = list(DIRECTION_8_NOUN_VOCAB.keys())
DIRECTION_8_BRIDGE_B_WORDS: List[str] = list(DIRECTION_8_VERB_VOCAB.keys())
DIRECTION_8_BRIDGE_C_WORDS: List[str] = list(DIRECTION_8_ADJECTIVE_VOCAB.keys())
DIRECTION_8_BRIDGE_D_WORDS: List[str] = list(DIRECTION_8_SPATIAL_VOCAB.keys())
DIRECTION_8_BRIDGE_E_WORDS: List[str] = list(DIRECTION_8_FUNCTIONAL_VOCAB.keys())

# Frozen union word order (cross-bridge probe at Task 4 consumes this).
# Iteration order: bridgeA (128 nouns) -> bridgeB (128 verbs) ->
# bridgeC (128 adj) -> bridgeD (128 spatial) -> bridgeE (128 functional)
DIRECTION_8_ALL_WORDS: List[str] = (
    DIRECTION_8_BRIDGE_A_WORDS
    + DIRECTION_8_BRIDGE_B_WORDS
    + DIRECTION_8_BRIDGE_C_WORDS
    + DIRECTION_8_BRIDGE_D_WORDS
    + DIRECTION_8_BRIDGE_E_WORDS
)

# Pre-registered total cross-bridge concept count
DIRECTION_8_TOTAL: int = 640

# Bridge -> {ordered words, ordered pool-names, builder-slot} map. Used by
# the bridge builder (Task 2) and the multi-seed runner (Task 5,
# controller-only).
DIRECTION_8_BRIDGE_CATALOG: Dict[str, Dict[str, object]] = {
    "A_nouns": {
        "words": DIRECTION_8_BRIDGE_A_WORDS,
        "pool_names": DIRECTION_8_NOUN_NAMES,
        "builder_slot": "noun_pool_names",
    },
    "B_verbs": {
        "words": DIRECTION_8_BRIDGE_B_WORDS,
        "pool_names": DIRECTION_8_VERB_NAMES,
        "builder_slot": "verb_pool_names",
    },
    "C_adj": {
        "words": DIRECTION_8_BRIDGE_C_WORDS,
        "pool_names": DIRECTION_8_ADJECTIVE_NAMES,
        "builder_slot": "adjective_pool_names",
    },
    "D_spatial": {
        "words": DIRECTION_8_BRIDGE_D_WORDS,
        "pool_names": DIRECTION_8_SPATIAL_NAMES,
        # Maps via noun_pool_names slot (no dedicated spatial pool kind
        # in the protected builder; concept-pool architecture is
        # category-agnostic at the pool level).
        "builder_slot": "noun_pool_names",
    },
    "E_functional": {
        "words": DIRECTION_8_BRIDGE_E_WORDS,
        "pool_names": DIRECTION_8_FUNCTIONAL_NAMES,
        # Same noun_pool_names slot mapping rationale as Bridge D.
        "builder_slot": "noun_pool_names",
    },
}
