"""Helpers for the 160-concept ensemble vocab-scaling arc.

The ensemble has 5 sparse-distributed bridges, each at 32 concepts.
This helper pulls each bridge's 32-word vocab from the existing
g20_vocab_spec (returning it verbatim, in spec order, never reshuffled)
and generates that bridge's sparse K-of-N patterns deterministically
via the validated `generate_sparse_patterns`. Per-bridge patterns are
seeded with a per-bridge derivative of the base seed (base XOR a
stable hash of the bridge name) so the 5 bridges' pattern sets are
decorrelated even at the same base seed -- a single seed value cleanly
seeds all 5 bridges to independent pattern sets.

Pure standard library + numpy (via the imported pattern generator);
deterministic; reuse-by-import only (g20_vocab_spec and the validated
generate_sparse_patterns are unchanged).
"""
from __future__ import annotations

import hashlib
from typing import List, Tuple

from research.runners.g20_vocab_spec import ALL_BRIDGES
from research.runners.concept_pool_sparse_distributed import (
    generate_sparse_patterns,
)

BRIDGE_NAMES = list(ALL_BRIDGES.keys())


def _bridge_seed(name: str, seed: int) -> int:
    """A deterministic per-bridge seed: base seed XOR a stable 24-bit
    hash of the bridge name. Keeps each bridge's pattern set
    independent of the others while remaining fully reproducible from
    (seed, name). The 24-bit mask keeps the result safely under
    2**24 so that downstream generators that multiply (e.g. the
    validated generate_sparse_patterns does seed * 17 + 19 internally)
    stay well within the uint32 range numpy RandomState accepts."""
    h = hashlib.sha256(name.encode("utf-8")).digest()
    return (int(seed) ^ int.from_bytes(h[:3], "big")) & 0xFFFFFF


def bridge_vocab_and_patterns(
    bridge_name: str, seed: int, n_pool: int, k: int,
) -> Tuple[List[str], List[List[int]]]:
    """Return ``(vocab, patterns)`` for one bridge of the 5-bridge
    sparse-distributed ensemble.

    ``vocab`` is the bridge's 32-word vocabulary from g20_vocab_spec
    returned in spec order (never reshuffled). ``patterns`` is a
    deterministic list of 32 sparse K-of-N patterns over ``n_pool``
    neurons (each pattern is a sorted list of K distinct neuron
    indices), generated by the validated `generate_sparse_patterns`
    seeded with the per-bridge derivative of ``seed`` so each
    bridge's patterns are decorrelated from the others.

    Raises ValueError for an unknown bridge name.
    """
    if bridge_name not in ALL_BRIDGES:
        raise ValueError(
            f"unknown bridge {bridge_name!r}; valid: {BRIDGE_NAMES}")
    vocab = list(ALL_BRIDGES[bridge_name])
    pats = generate_sparse_patterns(
        n_concepts=len(vocab), n_pool=n_pool, pattern_size=k,
        seed=_bridge_seed(bridge_name, seed))
    return vocab, pats
